### ISSUE TITLE
Unable to build KVMadm on openindiana/hipster

### ISSUE THREAD

**Issue by hput3** [hadfl/kvmadm#101]
I hope someone there will recognize the problem after reviewing this error received when building 
kvmadm on openinidana/hipster
root # /usr/bin/gmake install
Making install in thirdparty
gmake[1]: Entering directory '/usr/local/src/vcs/git/kvmadm/thirdparty'
  GEN    all-local
gmake[2]: Entering directory '/usr/local/src/vcs/git/kvmadm/thirdparty'
  GEN    touch
Found Illumos::Zones 0.1.4 which doesn't satisfy == 0.1.2.
Found Data::Processor 0.4.3 which doesn't satisfy == 0.4.2.
gmake[2]: *** [Makefile:359: touch] Error 123
gmake[2]: Leaving directory '/usr/local/src/vcs/git/kvmadm/thirdparty'
gmake[1]: *** [Makefile:356: all-local] Error 2
gmake[1]: Leaving directory '/usr/local/src/vcs/git/kvmadm/thirdparty'
gmake: *** [Makefile:404: install-recursive] Error 1

**Comment by hadfl** [comment]
should be fixed for 0.12.0
