### ISSUE TITLE
kvmadm list errors for non-mounted zones

### ISSUE THREAD

**Issue by citrus-it** [hadfl/kvmadm#105]
I have a number of zones on my server which are shutdown. Running `kvmadm list` produces errors as it tries to iterate the FMRIs within the zones. Since they are not even mounted, the repository is not accessible. Can the recent `svcs -Z` be used instead?

```
reaper# kvmadm list
svc.configd: Fatal error: /data/zone/hosting/root/etc/svc/repository.db: integrity check failed. Details in /etc/svc/volatile/db_errors
svccfg: Repository server failed (exit 102).
... repeated for each zone that is not running ...
```

**Comment by hadfl** [comment]
fixed: https://github.com/hadfl/kvmadm/pull/107
