### ISSUE TITLE
blocksize is 8k should be 128k on ssd disks

### ISSUE THREAD

**Issue by moetiker** [hadfl/kvmadm#110]
Hi 

We use 128k blocksize for ssd disks ...  it would be great if this could be configured in the 
kvmadm config property. 

"disk_blocksize" : "128K",     or   "volblocksize" : "128K"

**Comment by hadfl** [comment]
it can be defined already with `"block_size" : "..."` within a disk block:
https://github.com/hadfl/kvmadm/blob/master/lib/KVMadm/Config.pm#L216
