### ISSUE TITLE
Bug: console mode

### ISSUE THREAD

**Issue by sjorge** [hadfl/kvmadm#63]
Woops just remembered (by running into it) why I use minicom for the vt100 emulation.

1. passwords are echo'ed using kvmcli's console
2. terminal PS1 strings are garbled ( at least for smartos )
3. ctrl+xyz does not seem to be forwarded, ctrl+c terms the connection but not say a running command.

**Comment by hadfl** [comment]
hmm, i don't have a solution handy to get rid of all this whilst staying on core perl.

i think it might be best to deprecate the console option again.

if you connect to a console you want to use a proper VT10x emulation.

**Comment by sjorge** [comment]
How do you feel about telnet?

IIRC (not near my computer) socat to make it listen on a port, then telnet to it. Works I think.

**Comment by hadfl** [comment]
worth a try i think. will make a branch. would be great if you could test your use case then.

**Comment by sjorge** [comment]
Well it works (telneting to it), but still has the same issues :(
pulling console option is probably a good idea. I tried with an ubuntu vm that has a colored zsh prompt and same issue.

I'll keep my kvmcon around in my repo then.

**Comment by hadfl** [comment]
ok thanks. seems there is no way around a proper VT100 emulation.

going to nuke the console option until there is a satisfactory solution
