### ISSUE TITLE
support KVM in (linked) zones

### ISSUE THREAD

**Issue by hadfl** [hadfl/kvmadm#66]
add support to kvmadm to manage KVMs running in individual zones

**Comment by sjorge** [comment]
Nice! (Will this mean kvmadm will do zone setup also? Or just manage and instance inside a zone from the gz?)

**Comment by hadfl** [comment]
the plan is that kvmadm will also manage setup/config of zones. the idea is that kvmadm resides only in the global zone but will setup individual SFM instances in individual zones

**Comment by sjorge** [comment]
awesome idea! good luck.

**Comment by hadfl** [comment]
hey @sjorge it is almost ready --> https://github.com/hadfl/kvmadm/pull/72

i am doing last tests and a bit of cleanup before merging it. use it w/ caution since there has been a lot of rewriting!
