### ISSUE TITLE
hostname with - (dash)

### ISSUE THREAD

**Issue by moetiker** [hadfl/kvmadm#67]
hi

I did try the host name us-gw and kvmadm ends up with the error

[ Mar 31 15:04:39 Executing start method ("/opt/oep/bin/system-kvm start"). ]
Use of uninitialized value $kvmName in concatenation (.) or string at /opt/oep/bin/../lib/KVMadm/Config.pm line 243.

**Comment by hadfl** [comment]
fixed: https://github.com/hadfl/kvmadm/pull/69
