### ISSUE TITLE
"boot" : "true" / "boot" : "false"

### ISSUE THREAD

**Issue by moetiker** [hadfl/kvmadm#68]
boot false does not work. 

kvmadm  list usgw
..
         "boot" : "false",
         "disk_path" : "/dev/zvol/rdsk/fast/vm-volatile/us-gw/swap",

kvmadm  show-cmd usgw
..
-drive file=/dev/zvol/rdsk/fast/vm-volatile/us-gw/swap,if=virtio,media=disk,index=1,cache=none,boot=on

**Comment by hadfl** [comment]
fixed: https://github.com/hadfl/kvmadm/pull/70
