### ISSUE TITLE
boot has no default value

### ISSUE THREAD

**Issue by moetiker** [hadfl/kvmadm#71]
Hi

      {
            "index" : "1",
            "disk_path" : "/dev/zvol/rdsk/fast/vm/satellite/z-drive",
            "model" : "virtio",
            "disk_size" : "31G"
         },

if the disk has no boot value there is an error in the log file:
Use of uninitialized value in string eq at /opt/oep/bin/../lib/KVMadm/Config.pm line 331.
there should be a default value for boot.

..
. ($disk->{boot} eq 'true' ? ',boot=on' : ''));
..

cheers Manuel

**Comment by hadfl** [comment]
has already been fixed three days ago: https://github.com/hadfl/kvmadm/commit/52263ce48771e3a822875215bbeb0a1f7681e6ac
