### ISSUE TITLE
volblocksize and 4kn dirves

### ISSUE THREAD

**Issue by oetiker** [hadfl/kvmadm#91]
Having volumes with 8k volblocksize on 4k drives is rather inefficient. It can lead to up to 50% space loss ... since blocks are compressed, they will always be less than 8k but often more then 4k ... with 4k drives the allocation size is 4k.

We found (not excessively tested) that things look much better with 128k volblock size for such volumes. Space use is similar to the 8k volblocks on 512 disk blocks ...

There will probably be a performance penalty for small  read/writes ... but we also found the large reads at least are up to twice as fast as with 8k volblocks (probably due to the lower amount of wasted space)

see also zfsonlinux/zfs/issues/548

**Comment by hadfl** [comment]
--> https://github.com/hadfl/kvmadm/pull/92
