### ISSUE TITLE
cannot create zone - no brand 'lipkg'

### ISSUE THREAD

**Issue by bamdadkhan** [hadfl/kvmadm#94]
trying to create a vm (apparently that needs its own zone) on openindiana hipster, but there is no brand named 'lipkg', only the default 'ipkg' and solaris10 etc.

'lipkg' is omnios's brand for linked images - tried to use 'ipkg' instead but that wants to install the whole set of packages - hardly needed for a zone/vm running a different os.

man page didn't help a lot. am i missing the documentation on this?

thanks,
bamdad

**Comment by hadfl** [comment]
'lipkg' will install a full set of packages, too. but they are "tracked" w/ the global zone for easier upgrading.

i think apart from smartos no other illumos distro has "minimal zones for kvm". this is something which is not in the scope of kvmadm but in the distro itself.

you can always create and run the vm inside the global zone (just omit the zone part in the config).

**Comment by bamdadkhan** [comment]
thanks for the reply and the correction - and especially for indicating that i can omit the zone part. : ) closing issue.
