### ISSUE TITLE
kvmadm delete - zone purge deletes also kvm image -> kvmadm does not recognize

### ISSUE THREAD

**Issue by gumpp** [hadfl/kvmadm#96]
When deleting the VM "test2" with purging everything the following error messages are produced:

```
kvmadm delete --purge=vnic,zvol,zone test2
Are you sure you want to uninstall zone test2 (y/[n])? y
Are you sure you want to delete zone test2 (y/[n])? y
cannot open 'rpool/zones/test2/kvm0': dataset does not exist
ERROR: cannot destroy zvol 'rpool/zones/test2/kvm0'
```

Obviously the zone deletion also deletes the image file, which kvmadm does not recognize.
The KVM image is within the zone path, so the ZFS gets destroyed as well when the zone is purged:

```
rpool/zones/test2             10.8G   373G    19K  /zones/test2
rpool/zones/test2/ROOT         515M   373G    19K  legacy
rpool/zones/test2/ROOT/zbe     515M   373G   515M  legacy
rpool/zones/test2/kvm0        10.3G   384G     8K  -
```

_Recommended solution:_ Delete each zone's dataset separately.
Also, it might be possible that only the zone might be purged, not KVM image.

**Comment by hadfl** [comment]
ah i see. in my setup the kvm zvols are not within the zone tree. uninstalling the zone will delete all the subdatasets. so purge should delete the kvm zvols first before uninstalling the zone.

thank's

**Comment by hadfl** [comment]
zones get now purged last --> https://github.com/hadfl/kvmadm/pull/97
